strategy:
  asset_symbol: AAPL
  asset_class: equities
  rebalance_frequency: daily
  minutes_after_open: 30
  use_pipeline: false
  lookback_period: 30
  fast_period: 10
  slow_period: 30
position_sizing:
  max_position_pct: 0.95
  method: fixed
  volatility_lookback: 20
  volatility_target: 0.15
risk:
  use_stop_loss: true
  stop_loss_pct: 0.05
  use_trailing_stop: false
  trailing_stop_pct: 0.08
  use_take_profit: false
  take_profit_pct: 0.1
costs:
  commission:
    per_share: 0.005
    min_cost: 1.0
  slippage:
    volume_limit: 0.025
    price_impact: 0.1
backtest:
  data_frequency: daily
notes: 'Edit these parameters to customize the strategy.

  All values here override defaults from config/settings.yaml.


  When optimizing, modify parameter ranges, not individual values.

  See lib/optimize.py for optimization procedures.

  '
