# Strategy Parameters
# ==============================================================================
# All tunable parameters for this strategy.
# NO hardcoded parameters in strategy.py - everything comes from here.

# Strategy Configuration
strategy:
  asset_symbol: SPY              # Asset to trade (e.g., SPY, BTC-USD, EURUSD=X)
  asset_class: equities          # 'equities', 'crypto', 'forex'
  rebalance_frequency: daily    # 'daily', 'weekly', 'monthly'
  minutes_after_open: 30         # Minutes after market open to trade (0-60)
  lookback_period: 30            # Default lookback period for indicators

  # Pipeline Configuration
  # NOTE: Pipeline API is primarily designed for US equities with proper metadata.
  # Only set use_pipeline: true when:
  #   1. Asset class is 'equities' (US stocks)
  #   2. Bundle was ingested with 'country_code' column in asset metadata
  #   3. Strategy needs factor-based screening across multiple assets
  # For crypto/forex strategies, keep use_pipeline: false
  use_pipeline: false

  # Strategy-specific parameters
  # TODO: Add your strategy parameters here
  # Example:
  # fast_period: 10
  # slow_period: 30
  # trend_filter_period: 200

# Position Sizing
position_sizing:
  max_position_pct: 0.95         # Maximum portfolio allocation (0.0-1.0)
  method: fixed                   # 'fixed', 'volatility_scaled', 'kelly'
  
  # Volatility scaling (if method = volatility_scaled)
  volatility_lookback: 20         # Days for volatility calculation
  volatility_target: 0.15        # Target annualized volatility

# Risk Management
risk:
  use_stop_loss: true             # Enable stop loss
  stop_loss_pct: 0.05             # Stop loss percentage (0.01-0.10)
  
  use_trailing_stop: false        # Use trailing stop instead of fixed
  trailing_stop_pct: 0.08        # Trailing stop percentage
  
  use_take_profit: false          # Enable take profit
  take_profit_pct: 0.10           # Take profit percentage

# Costs (override defaults from config/settings.yaml if needed)
costs:
  commission:
    per_share: 0.005              # Commission per share
    min_cost: 1.0                 # Minimum commission per trade
  
  slippage:
    volume_limit: 0.025          # Max % of bar volume (2.5%)
    price_impact: 0.1             # Price impact coefficient

# Backtest Configuration
backtest:
  data_frequency: daily         # Data frequency for backtest: 'daily' or 'minute'

  # Warmup Period Configuration
  # The warmup period is the number of days needed before the strategy can generate signals.
  # This should be >= max(all indicator periods used in the strategy).
  # Example: For a 50/200 SMA crossover, warmup_days should be at least 200.
  # If not specified, calculated dynamically from strategy parameters.
  warmup_days: 30               # Minimum days of data before first signal (auto-calculated if null)
  validate_warmup: true         # Enable pre-flight warmup validation

# Notes
notes: |
  Edit these parameters to customize the strategy.
  All values here override defaults from config/settings.yaml.
  
  When optimizing, modify parameter ranges, not individual values.
  See lib/optimize.py for optimization procedures.

