# Test Hourly Momentum Strategy Parameters
# ==============================================================================
# This strategy is designed to test multi-timeframe data ingestion (1h data)
# using a simple SMA crossover approach.

strategy:
  asset_symbol: SPY
  strategy_type: momentum
  fast_period: 5     # Fast SMA period (in hourly bars)
  slow_period: 20    # Slow SMA period (in hourly bars)
  rebalance_frequency: daily
  minutes_after_open: 30
  use_pipeline: false

position_sizing:
  max_position_pct: 0.95
  min_position_pct: 0.0

costs:
  commission:
    per_share: 0.005
    min_cost: 1.0
  slippage:
    volume_limit: 0.025
    price_impact: 0.1

risk:
  use_stop_loss: true
  stop_loss_pct: 0.05
  use_take_profit: false
  take_profit_pct: 0.10

backtest:
  data_frequency: daily   # Strategy runs on daily schedule
  bundle_timeframe: 1h    # Bundle data is hourly (for reference)
  warmup_days: 30
