strategy:
  asset: 'SPY'
  rsi_period: 14
  rsi_oversold: 30
  rsi_overbought: 70
  rebalance_frequency: daily # Can be adjusted, but handle_data will run every minute due to schedule_function
  minutes_after_open: 1 # For scheduling non-handle_data functions
backtest:
  data_frequency: minute
costs:
  commission:
    per_share: 0.001
    min_cost: 0.10 # Lower for scalping
  slippage:
    volume_limit: 0.01 # Tighter for scalping
    price_impact: 0.05 # Tighter for scalping

